### ISSUE TITLE
Does not work on GitKraken 8.5.0

### ISSUE THREAD

**Issue by nolddor** [ColarWang/GitCracken#1]
```
$ node dist/bin/gitcracken.js patcher
```

It throws the error below:
```
==> 📦 Backup /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app.asar.1654585886598.backup
==> 🔓 Unpack /usr/share/gitkraken/resources/app.asar ➔ /usr/share/gitkraken/resources/app
==> 🔨 Patch /usr/share/gitkraken/resources/app with pro features
/home/user/git/user/GitCracken/GitCracken/dist/src/patcher.js:102
            throw new Error(`Can't patch ${patch.oldFileName}`);
                  ^

Error: Can't patch src/main/static/startMainProcess.js
    at Patcher.patchDirWithPatch (/home/user/git/user/GitCracken/GitCracken/dist/src/patcher.js:102:19)
    at Patcher.patchDirWithFeature (/home/user/git/user/GitCracken/GitCracken/dist/src/patcher.js:95:18)
    at Patcher.patchDir (/home/user/git/user/GitCracken/GitCracken/dist/src/patcher.js:89:18)
    at executeActions (/home/user/git/user/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:31:25)
    at Command.<anonymous> (/home/user/git/user/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:87:11)
    at Command.listener (/home/user/git/user/GitCracken/GitCracken/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:526:28)
    at Command.parseArgs (/home/user/git/user/GitCracken/GitCracken/node_modules/commander/index.js:665:12)
    at Command.parse (/home/user/git/user/GitCracken/GitCracken/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/user/git/user/GitCracken/GitCracken/dist/bin/gitcracken-patcher.js:89:6)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

```

**Comment by nolddor** [comment]
@wr00t / @PMExtra any ideas?

**Comment by PMExtra** [comment]
https://t.me/gitkrakencrackchat
